// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXDrWwIm3jRa6Kei3kMGKsyME_ACLW6V4',
    appId: '1:620846553089:web:b09bebc61d8fbc584a0800',
    messagingSenderId: '620846553089',
    projectId: 'satya2-app',
    authDomain: 'satya2-app.firebaseapp.com',
    storageBucket: 'satya2-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc0LcfvW0qHhICp3uOopMgsNftGefi_zA',
    appId: '1:620846553089:android:a3c3b15d14aa0c514a0800',
    messagingSenderId: '620846553089',
    projectId: 'satya2-app',
    storageBucket: 'satya2-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE2ZKAb_zAXrUrVypull7MV6wY1inbi9U',
    appId: '1:620846553089:ios:d9fdc6aebab84bc14a0800',
    messagingSenderId: '620846553089',
    projectId: 'satya2-app',
    storageBucket: 'satya2-app.firebasestorage.app',
    iosBundleId: 'com.example.satya2App',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE2ZKAb_zAXrUrVypull7MV6wY1inbi9U',
    appId: '1:620846553089:ios:d9fdc6aebab84bc14a0800',
    messagingSenderId: '620846553089',
    projectId: 'satya2-app',
    storageBucket: 'satya2-app.firebasestorage.app',
    iosBundleId: 'com.example.satya2App',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXDrWwIm3jRa6Kei3kMGKsyME_ACLW6V4',
    appId: '1:620846553089:web:9e6e91ff75e1f2264a0800',
    messagingSenderId: '620846553089',
    projectId: 'satya2-app',
    authDomain: 'satya2-app.firebaseapp.com',
    storageBucket: 'satya2-app.firebasestorage.app',
  );
}
